# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# 沙箱出口代理（依赖下载）
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=18080
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=18080
systemProp.http.nonProxyHosts=localhost|127.0.0.1

# Fabric（Yarn 映射）
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.19.3
fabric_version=0.141.6+1.21.11

# Mod
mod_version=4.0.0
maven_group=com.zijlo
archives_base_name=hopperfill
minecraft_dependency=>=1.21.11 <1.22
